Repository RBeerDevelopment/TINF18C_Team_4_AMLEngine-DLL-Interface, pull requests merged in 2020-04, with the labels that each got.

#50 Documentation/diagramms
  .gitignore
  EXECUTABLE/MOD_030_ConsoleApplication/Consolenapplikation.zip
  PROJECT/Pictures/Diagrams/Component_Diagram.png
  PROJECT/Pictures/Diagrams/aktivitaetsdiagrammValidation.png
Labels: documentation

#63 output.result -> to string
  SOURCE/MOD_020_JSWrapper/Node Projekt/src/Adapter/Adapter/Class1.cs
Labels: bug

#69 englisch pics & spelling
  SOURCE/MOD_010_C++Wrapper/docs/c++ wrapper/1_preparation.md
  SOURCE/MOD_010_C++Wrapper/docs/c++ wrapper/2_download_aml_engine.md
  SOURCE/MOD_010_C++Wrapper/docs/c++ wrapper/improved_screenshots/vs_installer_add_components.png
  SOURCE/MOD_010_C++Wrapper/docs/c++ wrapper/screenshots/vs_installer_add_components.png
  SOURCE/MOD_010_C++Wrapper/docs/c++ wrapper/screenshots/vs_installer_overview_en.png
Labels: documentation

#74 "I know all about waiting." ~ Rey
  SOURCE/MOD_010_C++Wrapper/docs/c++ wrapper/2_download_aml_engine.md
  SOURCE/MOD_010_C++Wrapper/docs/c++ wrapper/4_compiling.md
  SOURCE/MOD_010_C++Wrapper/docs/c++ wrapper/common_warnings.md
Labels: bug

#75 MANY Improvements
  SOURCE/MOD_030_ConsoleApplication/ConsoleApplication/ConsoleApplication/DeCompressor.cs
  SOURCE/MOD_030_ConsoleApplication/ConsoleApplication/ConsoleApplication/Options.cs
  SOURCE/MOD_030_ConsoleApplication/ConsoleApplication/ConsoleApplication/PrintHelper.cs
  SOURCE/MOD_030_ConsoleApplication/ConsoleApplication/ConsoleApplication/Program.cs
  SOURCE/MOD_030_ConsoleApplication/ConsoleApplication/ConsoleApplication/Validator.cs
Labels: enhancement

#76 fixed some common bugs
  SOURCE/MOD_020_JSWrapper/Node Projekt/dlls/Adapter.dll
  SOURCE/MOD_020_JSWrapper/Node Projekt/src/Adapter/Adapter/Class1.cs
  SOURCE/MOD_020_JSWrapper/Node Projekt/src/Adapter/Adapter/globalHelper.cs
Labels: bug
